### ISSUE TITLE
Whitelist Dell Latitude 7320

### ISSUE THREAD

**Issue by piotr152** [Wer-Wolf/i8kutils#8]
Hello and thank you so much for your work. I was seriously fed up with the BIOS controlled fan, how dare they? :)

I've finally gotten i8kutils to work on my Latitude 7320 and would like to request it being put on the official whitelist. Here are the lines I added to the module code

```c
	{
		.ident = "Dell Latitude 7320",
		.matches = {
			DMI_MATCH(DMI_SYS_VENDOR, "Dell Inc."),
			DMI_EXACT_MATCH(DMI_PRODUCT_NAME, "Latitude 7320"),
		},
		.driver_data = (void *)&i8k_fan_control_data[I8K_FAN_34A3_35A3],
	},
```

Not sure if the fan control data is correct. I've just copied it from the other Latitudes.

Last but not least, here's my dmidecode output. If you like, I'd be happy to know how you can read the fan control data from the log. I couldn't :)

[dmidecode.log](https://github.com/user-attachments/files/16174792/dmidecode.log)

All the best

**Comment by Wer-Wolf** [comment]
[dell-smm-hwmon.zip](https://github.com/user-attachments/files/16314694/dell-smm-hwmon.zip)

Sorry for taking a bit long to respond. Could you test the attached module and report if manual fan control works?

**Comment by piotr152** [comment]
It works perfectly, thank you very much.

**Comment by Wer-Wolf** [comment]
Very good, i will send the necessary patch then.

**Comment by Wer-Wolf** [comment]
The patch has been accepted and will land in kernel 6.12.

Have a nice day.
